use_frameworks!

platform :ios, '9.0'

target 'NVAccessibilitySolution_Example' do
  pod 'NVAccessibilitySolution', :path => '../'

  target 'NVAccessibilitySolution_Tests' do
    inherit! :search_paths

    
  end
end
